package com.masai.model;

public enum ProblemType {
	
	
	WITHDRAWAL,COUNSELLING_SUPPORT,MISSED_EVALUATION_SUBMISSION,LEAVE,MAC,PRODUCT_SUPPORT,CODING_PLATFORM,ATTENDANCE_QUERY,NBFC_ISA,COURSE_QUERY,ELECTIVES,REFERRAL
	
	

}
